Feature/fsd porowiec michal cs5
kamilwolczyk/fsd-second-edition pull request #39
Opened 2017-12-01 17:02 UTC by Michal-Porowiec

Tyle udało mi się zrobić. Zabrakło czasu na skończenie i optymalizowanie.

2017-12-10 10:41 UTC, kamilwolczyk requested changes
Gdzie jest zadanie nr 5?

2017-12-10 10:41 UTC, kamilwolczyk commented on src/porowiec-michal/Pzpn.Team/DupaDoUsunięcia/Program.cs
> +namespace DupaDoUsunięcia
usunąć

2017-12-11 18:22 UTC, Michal-Porowiec commented
W starej solucji. Jest to rozwinięcie projektu cs4

2017-12-14 15:27 UTC, kamilwolczyk approved these changes

2017-12-14 15:27 UTC, merged